<?php

namespace App\Console\Commands;

use App\Models\Food;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Http;

class ImportBaseFoods extends Command
{
    protected $signature = 'import:base-foods';
    protected $description = 'Imports a curated list of base foods from OpenFoodFacts API.';

    // A comprehensive list of common food items for a good baseline
    private array $baseFoodTerms = [
        // Früchte
        'Apfel',
        'Banane',
        'Orange',
        'Trauben',
        'Erdbeere',
        'Heidelbeere',
        'Avocado',
        'Zitrone',
        'Mandarine',
        'Clementine',
        'Birne',
        'Pfirsich',
        'Nektarine',
        'Kiwi',
        'Ananas',
        'Mango',
        'Melone',
        'Wassermelone',
        'Granatapfel',
        'Kirsche',
        'Zwetschge',
        'Aprikose',
        'Himbeere',
        'Brombeere',
        'Feige',
        'Dattel',
        'Johannisbeere',
        'Stachelbeere',
        'Papaya',
        'Passionsfrucht',
        'Limette',
        'Kokosnuss',
        'Mirabelle',
        'Quitte',
        'Grapefruit',
        'Physalis',
        'Cranberry',

        // Gemüse
        'Karotte',
        'Brokkoli',
        'Tomate',
        'Gurke',
        'Blattsalat',
        'Peperoni',
        'Zwiebel',
        'Knoblauch',
        'Spinat',
        'Zucchetti',
        'Aubergine',
        'Blumenkohl',
        'Rosenkohl',
        'Grünkohl',
        'Kopfsalat',
        'Eisbergsalat',
        'Lauch',
        'Stangensellerie',
        'Fenchel',
        'Randen',
        'Radieschen',
        'Mais',
        'Pilze Champignons',
        'Portobello Pilze',
        'Kürbis',
        'Kohlrabi',
        'Spargel grün',
        'Spargel weiss',
        'Chicorée',
        'Rucola',
        'Endivie',
        'Krautstiel (Mangold)',
        'Weisskohl',
        'Rotkohl',
        'Wirz',
        'Pak Choi',
        'Ingwer',
        'Chili',
        'Frühlingszwiebel',
        'Okra',
        'Artischocke',
        'Topinambur',

        // Kohlenhydrate & Getreide
        'Kartoffel',
        'Süsskartoffel',
        'Reis',
        'Vollkornbrot',
        'Zopf',
        'Spaghetti',
        'Penne',
        'Haferflocken',
        'Quinoa',
        'Linsen',
        'Kichererbsen',
        'Rösti',
        'Basmatireis',
        'Jasminreis',
        'Couscous',
        'Polenta',
        'Bulgur',
        'Tortilla Wrap',
        'Toastbrot',
        'Pita',
        'Knäckebrot',
        'Müsli',
        'Brezel',
        'Croissant',
        'Gipfeli',
        'Pizzateig',
        'Lasagneplatten',
        'Gnocchi',
        'Tagliatelle',
        'Tortellini',
        'Farfalle',
        'Fusilli',
        'Cannelloni',
        'Spätzli',
        'Dinkelbrot',
        'Roggenbrot',
        'Ciabatta',
        'Baguette',
        'Naan',
        'Grissini',
        'Reiswaffeln',
        'Cornflakes',
        'Weizentortilla',
        'Kamut',
        'Amaranth',
        'Basmati Vollkorn',
        'Wrap Vollkorn',
        'Taco Shells',

        // Proteine
        'Pouletbrust',
        'Rindshackfleisch',
        'Rindfleisch',
        'Schweinefleisch',
        'Kalbfleisch',
        'Lachs',
        'Thunfisch',
        'Ei',
        'Tofu',
        'Cervelat',
        'Schinken',
        'Speck',
        'Salami',
        'Forelle',
        'Sardinen',
        'Crevetten',
        'Miesmuscheln',
        'Seelachs',
        'Emmentaler Käse',
        'Feta',
        'Ricotta',
        'Mozzarella',
        'Camembert',
        'Gruyère',
        'Appenzeller Käse',
        'Bratwurst',
        'Kalbsbratwurst',
        'Weisswurst',
        'Mortadella',
        'Pouletflügel',
        'Poulet Schenkel',
        'Pouletgeschnetzeltes',
        'Rindsfilet',
        'Rindsentrecôte',
        'Kalbsgeschnetzeltes',
        'Schweinskotelett',
        'Fischstäbchen',
        'Poulet Nuggets',
        'Hackbraten',
        'Leberwurst',
        'Leberpastete',
        'Roastbeef',
        'Serrano Schinken',
        'Prosciutto',
        'Trutenbrust',
        'Lammfleisch',
        'Lammkoteletts',

        // Milchprodukte & Alternativen
        'Milch',
        'Joghurt Nature',
        'Quark Magerstufe',
        'Hüttenkäse',
        'Gouda Käse',
        'Käse',
        'Parmesan',
        'Butter',
        'Margarine',
        'Mandelmilch',
        'Sojamilch',
        'Hafermilch',
        'Schlagrahm',
        'Sauerrahm',
        'Crème fraîche',
        'Mascarpone',
        'Skyr',
        'Erdbeerjoghurt',
        'Vanillejoghurt',
        'Schokoladenjoghurt',
        'Actimel',
        'Kefir',
        'Buttermilch',
        'Laktosefreie Milch',
        'Halbrahm',
        'Kaffeesahne',
        'Philadelphia',
        'Streichkäse',
        'Fondue Käsemischung',
        'Raclette Käse',

        // Fette, Nüsse & Samen
        'Olivenöl',
        'Rapsöl',
        'Mandeln',
        'Baumnüsse',
        'Leinsamen',
        'Chia-Samen',
        'Sonnenblumenkerne',
        'Kürbiskerne',
        'Erdnüsse',
        'Cashewnüsse',
        'Pistazien',
        'Haselnüsse',
        'Kokosöl',
        'Sesam',
        'Tahin',
        'Walnussöl',
        'Avocadoöl',
        'Erdnussbutter',
        'Mandelbutter',

        // Getränke
        'Wasser',
        'Kaffee schwarz',
        'Coca-Cola Zero',
        'Coca-Cola',
        'Rivella blau',
        'Rivella rot',
        'Fanta',
        'Sprite',
        'Ice Tea Pfirsich',
        'Ice Tea Zitrone',
        'Apfelschorle',
        'Orangensaft',
        'Multivitaminsaft',
        'Bier hell',
        'Bier dunkel',
        'Weisswein',
        'Rotwein',
        'Prosecco',
        'Tee Pfefferminze',
        'Tee Kamille',
        'Tee Schwarz',
        'Tee Grün',
        'Energy Drink Red Bull',
        'Eistee Grüntee',
        'Tomatensaft',
        'Schorle Birne',
        'Most alkoholfrei',
        'Cider Apfel',
        'Cider Birne',
        'Glühwein',
        'Caotina',
        'Ovomaltine',
        'Mineralwasser mit Kohlensäure',
        'Mineralwasser ohne Kohlensäure',
        'Ice Coffee',
        'Protein Shake',

        // Sonstiges
        'Dunkle Schokolade 85%',
        'Honig',
        'Senf',
        'Ketchup',
        'Mayonnaise',
        'Salatsauce Französisch',
        'Salatsauce Italienisch',
        'Pesto Genovese',
        'Pesto Rosso',
        'Sojasauce',
        'Sriracha Sauce',
        'Essig Balsamico',
        'Essig Weisswein',
        'Bouillon Würfel',
        'Salz',
        'Pfeffer',
        'Paprikapulver',
        'Oregano',
        'Basilikum frisch',
        'Petersilie frisch',
        'Schnittlauch frisch',
        'Dill frisch',
        'Rosmarin frisch',
        'Thymian frisch',
        'Lorbeerblatt',
        'Zimt',
        'Vanilleextrakt',
        'Backpulver',
        'Natron',
        'Speisestärke',
        'Mehl Weiss',
        'Mehl Vollkorn',
        'Mehl Dinkel',
        'Mehl Mais',
        'Mehl Reismehl',
        'Puderzucker',
        'Kristallzucker',
        'Rohrzucker',
        'Agavendicksaft',
        'Ahornsirup',
        'Gelatine',
        'Agar Agar',
        'Hefe frisch',
        'Hefe trocken',
        'Paniermehl',
        'Maisstärke',
        'Tomatenmark',
        'Passierte Tomaten',
        'Pelati Tomaten',
        'Tomatensauce',
        'Currypaste Rot',
        'Currypaste Grün',
        'Kokosmilch',
        'Oliven schwarz',
        'Oliven grün',
        'Kapern',
        'Cornichons',
        'Essiggurken',
        'Apfelmus',
        'Birnenkompott',
        'Erbsen tiefgekühlt',
        'Spinat tiefgekühlt',
        'Pizza tiefgekühlt',
        'Pommes Frites tiefgekühlt',
        'Lasagne tiefgekühlt',
    ];

    public function handle()
    {
        $this->info('Starting import of base foods. This may take a few minutes...');

        $bar = $this->output->createProgressBar(count($this->baseFoodTerms));
        $bar->start();

        foreach ($this->baseFoodTerms as $term) {
            $response = Http::get('https://world.openfoodfacts.org/cgi/search.pl', [
                'search_terms' => $term,
                'search_simple' => 1,
                'action' => 'process',
                'json' => 1,
                'page_size' => 5,
                'search_tag' => 'nutrition_grades',
                'tagtype_0' => 'countries',
                'tag_contains_0' => 'contains',
                'tag_0' => 'switzerland',
            ]);

            if ($response->ok() && !empty($response->json()['products'])) {
                $product = $this->findBestProduct($response->json()['products']);

                if ($product) {
                    Food::updateOrCreate(
                        [
                            'source' => 'openfoodfacts',
                            'source_id' => $product['code'],
                        ],
                        [
                            'name' => data_get($product, 'product_name', $term),
                            'brand' => data_get($product, 'brands'),
                            'calories' => (int) data_get($product, 'nutriments.energy-kcal_100g', 0),
                            'protein' => (float) data_get($product, 'nutriments.proteins_100g', 0),
                            'carbohydrates' => (float) data_get($product, 'nutriments.carbohydrates_100g', 0),
                            'fat' => (float) data_get($product, 'nutriments.fat_100g', 0),
                        ]
                    );
                }
            }

            $bar->advance();
            sleep(1); // Be nice to the API
        }

        $bar->finish();
        $this->info("\nImport completed successfully!");

        return 0;
    }

    private function findBestProduct(array $products): ?array
    {
        return collect($products)->first(function ($product) {
            return !empty(data_get($product, 'product_name'))
                && !empty(data_get($product, 'nutriments.energy-kcal_100g'));
        });
    }
}